apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xsh9p3dgk-go 
  janus-idp.io/tekton: xsh9p3dgk-go
  backstage.io/kubernetes-id: xsh9p3dgk-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xsh9p3dgk-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml