apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: xsh9p3dgk-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xsh9p3dgk-go 
  name: xsh9p3dgk-go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: xsh9p3dgk-go
    weight: 100 
